### PR TITLE
Stop transmission cleanly, fix cron start

### LINKED ISSUE #24: Resume
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

Host OS: Ubuntu Server 16.04

I do not get the resume function in Transmission to work.
When restarting the Docker container I expect the ongoing torrent transactions to be resumed. Instead every torrent is removed. I can se that the resume directory contains multiple *.resume files. The files and directory are read and writable for everyone.

### LINKED ISSUE #39: Configuration file not save
When the container is stop/kill, the configuration file is not save and we loose all the modifications done with the GUI.

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

closes #24 
closes #39

### CODE REVIEW

**Comment by zaggash** [comment]
Why don't you use the "finish" script from S6  overlay  to handle the SIGTERM ?

**Comment by sparklyballs** [comment]
i'm not seeing any need for this

**Comment by zaggash** [comment]
Can't we use this ?

stage 3: This is the shutdown stage. Its purpose is to clean everything up, stop services and execute finalization scripts contained in /etc/cont-finish.d. This is when our init system stops all container processes, first gracefully using SIGTERM and then (after S6_KILL_GRACETIME) forcibly using SIGKILL. And, of course, it reaps all zombies :-).

**Comment by aptalca** [comment]
@sparklyballs unfortunately if there are active torrents, transmission does not stop when it receives a sigterm. Instead, it gets sigkilled by s6. When that happens, any changes to settings are not saved, and the partial torrents are lost. Upon restart, those torrents start downloading from scratch rather than resuming. This PR makes sure that transmission is stopped properly even when the are active torrents saving the settings and pausing the torrents. 

@zaggash cont-finish runs before s6-finish and stopping processes during cont-finish creates a race condition where s6 might relaunch the process after cont-finish stops it (because s6 might still be trying to keep it up at that point). I tried it with the mariadb container and had issues. With the trap, "s6-svc -d" generated sigterm results in a clean stop

**Comment by lordjancso** [comment]
@j0nnymoe when will you merge this one?

**Comment by norrin77** [comment]
Having same issue. I would like to limit my upload bandwith and keep this setting upon restart.

**Comment by lordjancso** [comment]
@sparklyballs what is up with this issue? it is getting more annoying since the possible solution is here.

**Comment by onedr0p** [comment]
@sparklyballs 
> i'm not seeing any need for this

Care to explain?

**Comment by neothematrix** [comment]
hi, it seems the change to the run script made in this PR breaks the handling of sighup signals sent after the crontab that updates the blocklists, everytime a HUP signal is sent to the daemon, a new transmission-daemon process is created and the processes will start stacking, does this happen only to me?

**Pull request merged**
