### PR TITLE
Default directories are created only if needed

### PR DESCRIPTION
**Pull request by hacketiwack**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-transmission/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

The objective of this change is to avoid the creation of the different default directories: for downloads, incomplete downloads, and the watch folder.
Indeed, even if the user has defined their directories, the default ones are annoyingly always created.

## Benefits of this PR and context:

This change checks if there is already an existing `/config/settings.json` file and if yes, uses the configured directories.
If there are no directories configured, then values for the directories defined in `/defaults/settings.json` are taken.

Moreover, the file has been simplified to be more readable and using the `jq` command (which is installed anyway) instead of less safe `sed` replacements.

## How Has This Been Tested?

Built with my own CI/CD pipeline on Azure DevOps and deployed on my test rig.

### CODE REVIEW

**Comment by hacketiwack** [comment]
Solves [this issue](https://github.com/linuxserver/docker-transmission/issues/200).

**Comment by hacketiwack** [comment]
Is there still someone maintaining this repository?

**Comment by hacketiwack** [comment]
Is this repository still active?

**Comment by tan-wei** [comment]
Humm, inactive?

**Comment by hacketiwack** [comment]
> Humm, inactive?

It seems so... There's no news whatsoever...

**Comment by aptalca** [comment]
I'll be honest. I'm not touching this PR because:
1. It combines two separate things: handling of download folders and switching sed to jq
2. I don't view the creation of download folders as an issue that needs a solution
3. Switching sed to jq seems to be merely cosmetic and doesn't add real benefit, but adds risk due to potential issues with the code, and increases maintenance burden if the maintainer is not that familiar with jq

**Comment by hacketiwack** [comment]
Thanks for the reply.

1. OK. Acknowledged.
2. It is not a big issue that the directories are created. It is just not so nice considering the user has a different configuration, the pre-defined directories are recreated at each relaunch of the container.
3. OK, fair enough regarding the use of jq. It was simplifying things in my opinion. I will create a pull request that uses the sed.

**Comment by drizuid** [comment]
closing this as we do not see a benefit to our userbase by accepting it. Users are free to use whatever folders they wish for downloads/incomplete. the existence of an empty directory does not preclude this.

**Pull request closed without merging**
