### PR TITLE
Add network type

### PR DESCRIPTION
**Pull request by overbid**
From my experience w/o net=host sometime container didn't work.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by tobbenb** [comment]
It doesn't need net=host as long as you map the used ports.

**Comment by overbid** [comment]
[2017-03-18 05:40:33.567] some.file Scrape error: Could not connect to tracker (announcer.c:1279)
[2017-03-18 05:40:33.567] some.file Retrying scrape in 20 seconds. (announcer.c:1288)

Without --net=host transmission can't reach torrent.

**Comment by tobbenb** [comment]
Then you are most likely not adding the correct port to the docker run command.

**Comment by aptalca** [comment]
Not too familiar with how trackers work, but IIRC, user connects to the tracker to retrieve the IPs of other users.

Net=host setting only affects incoming connections to the container. It allows all ports to be forwarded to the container. Mapping a port only allows that port to be forwarded, other port requests do not reach the container.

If my assumption is correct and the tracker connection is a outgoing one, the net=host setting would likely have no effect on it.

**Pull request closed without merging**
