### PR TITLE
Add flood-for-transmission as an alternative UI

### PR DESCRIPTION
**Pull request by johman10**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-transmission/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

I'm the creator of Flood for Transmission. And I was hoping that you would be willing to include this alternative UI as an option in your build. Hence why I decided to create a PR.

Flood for Transmission is feature complete and has all the features the default Transmission UI does. I noticed there is already other alternative UI's so I don't think it is too much of stretch from your usual UI.

Do feel free to check out the UI here: https://github.com/johman10/flood-for-transmission/tree/master/screenshots#readme.

I also figured to properly link to the Github repositories of the alternative UI's to ensure people can find the place to go whenever they need help or have find a bug in the UI.

## Benefits of this PR and context:

A fresh, new and feature complete UI to pick from.

## How Has This Been Tested?

1. Build the container with: `docker build --no-cache --pull -t transmission .`
2. Run the container with: `docker run -d --name=transmission -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -e TRANSMISSION_WEB_HOME=/flood-for-transmission/ -p 9091:9091 -p 51413:51413 -p 51413:51413/udp -v ~/Downloads:/config -v ~/Downloads:/downloads -v ~/Downloads:/watch --restart unless-stopped transmission`
3. Open the browser at [localhost:9091](http://localhost:9091) and see that Flood for Transmission is properly displayed

### CODE REVIEW

**Comment by johman10** [comment]
This slows down the builds more significantly than I expected. This probably has to do with the fact the flood-for-transmission doesn't have the build files in the repo.

I think it may be better if I start adding those to my repo so processes like this can be sped up. I'm looking into a solution for this.

Please let me know if you're willing to accept a PR if the build version is part of the repo and it would work similarly to the others. If so I will come back to update this PR.

Hope to hear from you!

**Comment by johman10** [comment]
This should now use the latest release that I build on every push to master.

Please consider merging this when you have a moment. :)

**Comment by johman10** [comment]
Please keep this open and consider it for a review. :)

**Comment by Cryotize** [comment]
This is amazing, i was about to do the same!

**Review by aptalca — APPROVED** [review]

**Comment by johman10** [comment]
Thanks for the merge @aptalca! 🎉

**Comment by aptalca** [comment]
@johman10 thanks for the PR. Apologies for not getting to it earlier

**Pull request merged**
