### PR TITLE
Added the missing UMASK section.

### PR DESCRIPTION
**Pull request by uhop**
See https://github.com/linuxserver/docker-transmission/issues/272

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-transmission/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Trivial 3-line section to set `UMASK` to `settings.json` as per the current documentation.

## Benefits of this PR and context:

It fixes the filed bug, which clearly annoys people (including me).

## How Has This Been Tested?

I ran it and saw the change in `/config/settings.json`.

## Source / References:

The existing doc: https://github.com/linuxserver/docker-transmission/blob/a63cd602e62ea3418ee416a064cc6a0a8f45ffc6/README.md?plain=1#L177

The bug: #272

### CODE REVIEW

**Comment by zwimer** [comment]
Thanks for addressing this issue, I currently run a script that periodically chmod's stuff so I'm glad I'll soon be able to get rid of that :)

**Comment by positiveque** [comment]
> Thanks for addressing this issue, I currently run a script that periodically chmod's stuff so I'm glad I'll soon be able to get rid of that :)

Could you share your script? Thanks.

**Comment by nemchik** [comment]
My only thought here is I would recommend doing it via `jq` rather than `sed` in case anything about the settings.json changes in a way that breaks the `sed` pattern. `jq` should be more resilient in that regard.

**Comment by uhop** [comment]
> My only thought here is I would recommend doing it via `jq` rather than `sed` in case anything about the settings.json changes in a way that breaks the `sed` pattern. `jq` should be more resilient in that regard.

Sounds like a good idea, but take a look at the modified file: https://github.com/linuxserver/docker-transmission/blob/20cf81ec2e49fec458e140de6b32f0d733094c47/root/etc/s6-overlay/s6-rc.d/init-transmission-config/run

It uses `sed` 16 times. I added the change (one more use of `sed`) in the same style to be consistent, to reduce possible dependencies and to lessen the cognitive load on future maintainers.

If you want to rewrite the whole file (and other files?) &mdash; please let me know. I would recommend retooling and reimplementation as a separate PR as the orthogonal thing not directly related to the bug.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
