### PR TITLE
Added optional env variable: SCRIPT_TORRENT_DONE_FILENAME

### PR DESCRIPTION
**Pull request by scalerow**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x ] I have read the [contributing](https://github.com/linuxserver/docker-transmission/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

**Optional env variable that sets script-torrent-done-filename and enables script-torrent-done-enabled :**
- New envirnonment variable : SCRIPT_TORRENT_DONE_FILENAME

## Benefits of this PR and context:

**It would be usefull with easier access to script-torrent-done-filename through this env variable, as that would simplify automation.**

**Considering the some usecases and challanges you can run into when torrenting:**
- It's not uncommon for torrents to come packaged into several files - this causes problems with importing to other services like sonarr and radarr, running a script to unpack on download-complete would be helpfull. 
- When using transmission without any connected services some might find it usefull to run a script for cleanup, moving the file elsewhere etc.

## How Has This Been Tested?

**Manual testing:** 
- Running on headless Ubuntu Server 23.04, Docker 24.0.4, Docker Compose 2.19.1.
- Built image according to your "Building image locally" howto.
- Deployed using compose script both with and without the new env variable, and verified the results in settings.json.
- Currently running "live" on my server.

### CODE REVIEW

**Comment by aptalca** [comment]
Why not just set it in the config file? It's user configurable

**Comment by scalerow** [comment]
> Why not just set it in the config file? It's user configurable

I would argue it’s more convenient and automation friendly, beeing able to set it once with ease in f.ex a compose script, without having to worry about extra files/resources than necessary. Furthermore, since I suspect a lot of people are using Transmission paired with Radarr/Sonarr, which cannot import divided rars, I think it makes sense to resolve the issue before import, hence making it as obvious and convenient as possible!

I might not be right, but that’s my reasoning :)

**Comment by scalerow** [comment]
Should I abort this PR, or leave it up?

**Comment by drizuid** [comment]
> Should I abort this PR, or leave it up?

Sorry for the delays in getting back to you, our backlog is quite big. We are not fans of having a ton of envvars as for the majority of our userbase, it's simply too confusing for them and poses a support nightmare for us. We will not merge this in, however, thank you for your time and effort spent creating this PR, testing it, and providing your input! While we're not accepting this PR, we still appreciate those who put in the effort!

**Pull request closed without merging**
