### PR TITLE
Feature mail notification ssmtp

### PR DESCRIPTION
**Pull request by Turgon37**
This PR is next to the previous one #20 
I propose to include a base notification script, written in bash, which allow the transmission daemon to send mail when a torrent has finished to download. This script use ssmtp as a lightweight smtp client.

I've made the required modification in the root/ of the container. The script itself has been tested by myself on instance of your image. The configuration is made at each 'service' restart. and it is fully based on the environment variables

### CODE REVIEW

**Comment by sparklyballs** [comment]
jenkins test this please

**Comment by Turgon37** [comment]
Why do you not want the mail feature to be configurable by env variables ?
I think that docker's concept is to provide the most of the configuration keys by env variables to make easier the scalability and reduce the need to use 'docker exec'

**Comment by sparklyballs** [comment]
don't have to use docker exec at all.
the init file copies ssmtp.conf to /config
user edits it, restarts the container and the init copies it to /etc/

**Comment by Turgon37** [comment]
If the /config is mapped to a docker volume the only 'proper' way to edit files in is to use something like "docker exec transmission vi /config/...."

**Comment by sparklyballs** [comment]
no it isn't lol.
any local editor to the host os will be fine
with the cp back to /etc can make the permissions correct etc.

it's preferable to adding a load of variables to the run command

**Comment by Turgon37** [comment]
I don't really see how you can just "edit with a local text editor' because all files whose are in /config folder of the container are stored in the /var/lib/docker/volume/XXXXX/_data (if you really use the docker volume feature and not a simple mounted path from the host)
So my philosophy is to provide to more simple way to user to configure his container. As a result with a correctly written Docker-compose file four or five environment variables are more easy to use that a manual configuration of files in /config.
Consider the case where you are mandatory to re-install completly your container. With my solution, you simply have to run 'docker-compose up -d' (with your backup docker-compose file). 
With your's, you have to 'docker run' the container and to make some configurations files' editions like before docker arrive in the IT world.
As I have read in docker manuals, docker volumes are only use to store applications datas and optionally application configurations, but not for configurations which concerns external world of the container. As an example, in our case, the settings.json is correctly store into the docker volume because it concerns the application transmission itself but the SMTP configuration concerns the mail server/relay with is obviously outside of the container.

I will update my PR according to your remarks but in fact I don't agree with the manner of you handle the SSMTP configuration

**Comment by Turgon37** [comment]
Hello,

Updates performed, you can evaluate

**Comment by sparklyballs** [comment]
jenkins retest this please

**Comment by sparklyballs** [comment]
closing this

**Pull request closed without merging**
