### PR TITLE
Allow for custom Blocklist update scripts located in /config

### PR DESCRIPTION
**Pull request by quinnsam**
After the pull request  #99 where the update script is internalized it is hard to have a custom script run like before. I have a script that concatenates multiple URLs from different sources into one file. This pull request will add support for executing `/config/blocklist-update.sh` if it exists. If the custom script doesn't exist in the `/config` folder the original script is executed. 

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:

I have modified the `/root/app/blocklist-update.sh` script to allow for custom scripts located in the `/config` folder. After the latest change where this script was internalized, I am no longer able to execute a custom script to update the blocklists for transmission. There are multiple blocklists that can be useful, by allowing custom scripts to be executed it will allow users to download multiple blocklists and apply them to Transmission.

## Benefits of this PR and context:

This script doesn't change any default functionality but adds the option to run user scripts to configure the blocklists. 
## How Has This Been Tested?

Yes, I have added a debug message that can be toggled, default off. I have also tested with custom scripts and using the existing functionality of using a `blocklist-url` from the `settings.json`.

### CODE REVIEW

**Comment by nemchik** [comment]
Thanks for taking the time to write this up. I actually think this is less common and would be better accomplished on an individual level by reading https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

You could add script to `/config/custom-cont-init.d/` (these fire when the container starts) that replaces https://github.com/linuxserver/docker-transmission/blob/fa57c2b4800380abeff7dcdd19108dea5cd49672/root/etc/crontabs/root#L10 in `/etc/crontabs/root` inside the container with 
```
 0 3 * * * /config/blocklist-update.sh 2>&1 
```

It would likely be easily accomplished by a line like
```
sed -i 's/app/config/' /etc/crontabs/root
```
but I would encourage you to tweak that and improve the accuracy of the search/replace (just wanted to give a conceptual example).

**Comment by aptalca** [comment]
Or even a docker mod that injects a custom script into `/app/blocklist.sh`

**Comment by nemchik** [comment]
Worth noting the behavior has changed in https://github.com/linuxserver/docker-transmission/pull/106
A docker mod is absolutely an option, but it would probably do as I described above (replace the cron line to run a different script). This will be the safest option so that any further changes we do internally to `/app/blocklist-update.sh` don't affect you.

**Comment by quinnsam** [comment]
Yeah, I was sort of thinking the same thing but I didn't know if it was common practice for customizations to overwrite default functionality or not. I appreciate the suggestions and will try them out!

**Comment by nemchik** [comment]
Yes! We can't offer direct support for the functionality of what you choose to do with your modifications, but if you feel confident with the modifications (evident from your PR, it was well written) you should be perfectly fine to hack away at the container!

**Pull request closed without merging**
